services:

  keycloak:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloakdb
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=localhost

      # set admin to localhost access
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin@123
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
    volumes:
      - ./data/postgresql:/var/lib/postgresql